name: Daily Python Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create or reset auto-update branch
        run: git checkout -B auto-update-branch

      - name: setup python
        uses: actions/setup-python@v5
      
      - name: Run script
        run: python3 .github/python_scripts/update_IG.py
         
      - name: Commit changes if any
        run: |
          git diff --cached --quiet || git commit -m "Update tool.py from remote $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f origin auto-update-branch

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v7.0.8
        
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-update-branch
          base: main
          title: "Update: IG daily sync"
          body: "This PR updates the IG"
          commit-message: "Automated update of IG"
          update-existing: true
